### PR TITLE
Update to teal3

### PR DESCRIPTION
**Pull request by barnjamin**

### CODE REVIEW

**Comment by barnjamin** [comment]
This is the output from `make` command in go-algorand/data/transactions/logic

**Comment by emg110** [comment]
Thanks @barnjamin , I took the privilege of reusing your commit as part of mine after updating it, I appreciate it.

Any chance you could follow up your PR with ObsidianLabs folks? It's pretty timey given the major version change and there is no activity! May be you can propose to them a new maintainer assignment or one of us activate a fork as replacement if they have lost the desire to go on! This repo is very important given the tendency of community to VSCODE, don't you agree @barnjamin?

**Comment by barnjamin** [comment]
Yea, its definitely useful for me and I expect others will also find it useful.  Also a pain to have to come in here and figure out that the necessary highlighting is in a PR.

I'm not sure who to bug about it though.

**Comment by emg110** [comment]
Dear Benjamin
Let me explain once more, the person you need to start communication with
is  ***@***.***, he is head of business opportunities
division and I just got his email from Russ, OK? I did not tell David about
your case in order to avoid any confusion so all you need to do is send him
an email and present your case . Have a nice day dude.

Best Regards
-------------------------
*M.Ghiasi*
Technology Architect
-------------------------
*"COVID-19 Kills! Wear a mask & regularly wash your hands to save the
world!"*

**Pull request closed without merging**
